### ISSUE TITLE
Checking and display of Enumerated value properties 

### ISSUE THREAD

**Issue by MatthiasWeise** [xBimTeam/XbimMvdXML#1]
It seems that IFCPROPERTYENUMERATEDVALUE is not properly checked and not shown in the property tab. 

This is an example:
#2739=IFCSPACE('1joJMsuM0e2DPoYGiOkFYq',#5,'Day care room',$,$,#2740,#2743,'Day care room',.ELEMENT.,.NOTDEFINED.,$);
#2755=IFCPROPERTYENUMERATEDVALUE('AccessSecurity',$,(IFCLABEL('A2')),#2552);
#2552=IFCPROPERTYENUMERATION('AccessSecurity',(IFCLABEL('A1'),IFCLABEL('A2'),IFCLABEL('A3'),IFCLABEL('A4'),IFCLABEL('A5')),$);
#2760=IFCPROPERTYSET('2mIneNqiyLlXIvmv5QIyMx',#5,'STREAMER_Labels_PoR',$,(#2755));
#170088=IFCRELDEFINESBYPROPERTIES('2oODzCyK8c_aL_5xT1AIbm',#5,$,$,(#2739),#2760);

Attached the full IFC file.
[Step02_EDC_Output_correct_enums.txt](https://github.com/xBimTeam/XbimMvdXML/files/575832/Step02_EDC_Output_correct_enums.txt)

and the mvdXML.
[PoR_EnumCheck_IFC2X3_V4_update.txt](https://github.com/xBimTeam/XbimMvdXML/files/575838/PoR_EnumCheck_IFC2X3_V4_update.txt)

**Comment by CBenghi** [comment]
Hello @MatthiasWeise,
I will fix xplorer to display the value of enumerated properties, but at a first inspection it looks like if the mvdxml engine actually sees the properties correctly.
Can I ask which is the ID of the test that is behaving unexpectedly?

Edit: on second ispection I've seen that there might be a problem with the value of the enumeration; however it would still help to know the id of the test.

**Comment by MatthiasWeise** [comment]
There are many tests against enumeration values. May use the first one: 
`<Concept uuid="00000003-0000-0000-0000-000000349910" name="Accessibility Labels">`
Any space instance except Corridor should have that property. May check the following:
`#2534=IFCSPACE('3eiIkfzHDJUV_zUUzGg86Q',#5,'Health manager office',$,$,#2535,#2538,'Health manager office',.ELEMENT.,.NOTDEFINED.,$); `

**Comment by CBenghi** [comment]
Hello @MatthiasWeise,
I've changed the Xplorer UI to display the enumerated values in the property box.
However this was only an UI change and it seems to me that the mvdxml engine works properly on the enumerations that you have referenced above:

![image](https://cloud.githubusercontent.com/assets/5476273/20947058/4cbea258-bc05-11e6-941a-2646ff735d63.png)

I've attempted to colour the spaces accorging to the single concept that you list and all spaces pass, except the corridors, as you would expect.

![image](https://cloud.githubusercontent.com/assets/5476273/20947116/96bdd450-bc05-11e6-9ca5-970cd7b77650.png)

I think this also makes for quite a X-massy picture :)

Is there something I'm not getting?

**Comment by CBenghi** [comment]
Hello again,

I'm uploading the latest version of Xplorer to https://dl.dropboxusercontent.com/u/38347707/ReleaseV4.exe
The mvdplugin can be downloaded and enabled through the settings page (View/Settings on the menu). 

The plugin downloading mechanism is experimental but it should work, I've tested it on a few machines. Let me know if you are having problems. 

Feedback on the plugin installation interface is also welcome (although still in beta, and I know there's much to do).

Best,
Claudio

**Comment by MatthiasWeise** [comment]
Thanks Claudio!
Checking of enum values seem to work now (properly shown and checking result is ok). 

Conceptually it is ofcourse questionable if enum values should be checked via mvdXML if defined by IfcPropertyEnumeratedValue. In that case proper use of enum values is enforced by the IFC schema (WR21). I guess the following definition should be marked as error when importing the IFC file:  
`#2550=IFCPROPERTYENUMERATION('HygienicClass',(IFCLABEL('H1'),IFCLABEL('H2'),IFCLABEL('H3'),IFCLABEL('H4'),IFCLABEL('H5')),$);
#2551=IFCPROPERTYENUMERATEDVALUE('HygienicClass',$,(IFCLABEL('H6')),#2550);`

**Comment by CBenghi** [comment]
The plan is to enable validation of models in Essentials with the Where clauses fairly soon, I've already done some work on this, but it's difficult to predict how much more is needed.
