### ISSUE TITLE
Can't find missing packages from your package server

### ISSUE THREAD

**Issue by ghost** [xBimTeam/XbimMvdXML#13]
I don't compile the project. Because I don't find dependent dlls from any url.
![image](https://user-images.githubusercontent.com/23723575/121466617-4d385600-c9ea-11eb-8f31-b7a52070b717.png)

**Comment by yuancustom** [comment]
Yes，I cannot compile too！

**Comment by CBenghi** [comment]
Hi all,
have a look at latest develop branch.
I've just pushed an update that should fix.

**Comment by ghost** [comment]
Thanks.
