### ISSUE TITLE
Error loading mvdXML plugin

### ISSUE THREAD

**Issue by thorstenlang** [xBimTeam/XbimMvdXML#2]
Thank you for making this available. I've tried loading mvdXML plugin in Xbim, but get an error.  I’m attaching the log-file, the error is mentioned on line 217 through 229.
My system is Windows 10 on a Bootcamp partition on a MacBook Pro 2011.

Best regards,

Thorsten Lang

[mvdXML loading error.txt](https://github.com/xBimTeam/XbimMvdXML/files/741805/mvdXML.loading.error.txt)

**Comment by CBenghi** [comment]
Hello Thorsten,
I've pushed updates for bot WindowsUI and the MvdXML packages today.
MvdXML was not synchronised with the latest WindowsUI development, but it should be fixed now. Please download from the develop branch for your tests.
(If you use develp WindowsUI you should be able to download the latest plugin form the settings page.

BTW, MvdXML is quite experimental at the moment, I think you are one of few people using it.
I'd be interested in a chat to understand how you use it and how it can be improved. Let me know if we can have a chat.
Best,
Claudio

**Comment by thorstenlang** [comment]
Dear Claudio,
I still have to try using mvdXML, I am working with Matthias Weisse of AEC3 on a european project (http://streamer-project.eu/) for which he produced an mvdXML file. He also sent me a self-extracting Xbim zip. Before I had tried with Visual Studio and NuGet, but I wasn’t sure on how to assemble the packages.
I would be happy to chat with you, please contact me on Skype, my skypename is: thorstenlang

Thank you.

Best regards,


Thorsten Lang

**Comment by CBenghi** [comment]
Good.
I'll get in touch tomorrow to provide the latest files.
 Best
Claudio

**Comment by CBenghi** [comment]
Hello again,
for the updated version please download and extract
https://dl.dropboxusercontent.com/u/38347707/ReleaseV4.exe

You'll then be able to install the mvdxml plugin from the view/settings page, then selecting the plugin tab.
BTW, in the plugin section I'd advise you to use the BCFier plugin instead of the legacy BCF editor for the collaboration format.

Let me know if you still find problems. 

Best,
Claudio
