### ISSUE TITLE
Error Message when testing Model against created mvdXML

### ISSUE THREAD

**Issue by TobTob-BIM** [xBimTeam/XbimMvdXML#7]
Hello xBIMTeam!

I am currently experimenting with the IfcDoc Tool and mvdXML. All my test with the example files went well, thanks for providing them!

I now tried to create my own mvdXML using the IfcDoc Tool and it seems like I am unable to create a proper file for Xbim. At the moment when I try to run my tests the following error messages show up:

**==== 14:32	ERROR	XbimPlugin.MvdXML.MainWindow
Error processing entity #672.
Der Wert darf nicht NULL sein.
Parametername: source
   bei System.Linq.Enumerable.Distinct[TSource](IEnumerable`1 source)
   bei Xbim.MvdXml.TemplateRules.GetIndicators()
   bei Xbim.MvdXml.ConceptRootApplicability.get_DataIndicators()
   bei Xbim.MvdXml.ConceptRootApplicability.GetData(IPersistEntity entity)
   bei Xbim.MvdXml.ConceptRootApplicability.IsApplicable(IPersistEntity entity)
   bei Xbim.MvdXml.Concept.AppliesTo(IPersistEntity entity)
   bei Xbim.MvdXml.Concept.Test(IPersistEntity ent, ConceptTestMode mode)
   bei Xbim.MvdXml.RequirementsRequirement.Test(IPersistEntity ent)
   bei XbimPlugin.MvdXML.MainWindow.ReportRequirementRequirement(RequirementsRequirement requirementsRequirement, IPersistEntity entity)
   bei XbimPlugin.MvdXML.MainWindow.PerformReport(HashSet`1 selectedConcepts, HashSet`1 selectedExchReq, HashSet`1 selectedIfcClasses, List`1 entities, MvdEngine doc, Object sender, DoWorkEventArgs ea, ObservableCollection`1 destinationResultCollection, BackgroundWorker reportingWorker, HashSet`1 requiredReportingSet)**

It seems like a certain value is not allowed to be equal NULL, but as far as I know, I am following all the rules for creating an mvdXML using the IfcDoc Tool. Are there certain restrictions requirements for a mvdXML to work with xBIM?
When looking at the example mvdXMLs, most of the were created by AEC3, I guess by using their database behind BIMQ. Is there a major difference between their creation process for mvdXML?

Best regards,

Tobias

**Comment by CBenghi** [comment]
Hi Tobias,
Is there a minimal test file that you can share to reproduce the issue?
Thanks,
Claudio

**Comment by TobTob-BIM** [comment]
Hi Claudio,

thank you for your quick response. I build a very small mvdXML and was testing it against one of the provided test models, both files are included in the attached .zip

This time the error says:
_==== 16:09	ERROR	XbimPlugin.MvdXML.MainWindow
Error processing entity #161.
Der Wert darf nicht NULL sein.
Parametername: source
   bei System.Linq.Enumerable.Distinct[TSource](IEnumerable`1 source)
   bei Xbim.MvdXml.TemplateRules.GetIndicators()
   bei Xbim.MvdXml.ConceptRootApplicability.get_DataIndicators()
   bei Xbim.MvdXml.ConceptRootApplicability.GetData(IPersistEntity entity)
   bei Xbim.MvdXml.ConceptRootApplicability.IsApplicable(IPersistEntity entity)
   bei Xbim.MvdXml.Concept.AppliesTo(IPersistEntity entity)
   bei Xbim.MvdXml.Concept.Test(IPersistEntity ent, ConceptTestMode mode)
   bei Xbim.MvdXml.RequirementsRequirement.Test(IPersistEntity ent)
   bei XbimPlugin.MvdXML.MainWindow.ReportRequirementRequirement(RequirementsRequirement requirementsRequirement, IPersistEntity entity)
   bei XbimPlugin.MvdXML.MainWindow.PerformReport(HashSet`1 selectedConcepts, HashSet`1 selectedExchReq, HashSet`1 selectedIfcClasses, List`1 entities, MvdEngine doc, Object sender, DoWorkEventArgs ea, ObservableCollection`1 destinationResultCollection, BackgroundWorker reportingWorker, HashSet`1 requiredReportingSet)_

It is pointing me to the entity #161 which is an IfcWallStandardCase in the included IFC-file. In attached mvdXML I set two requirements for the values of the attributes "Name" and "ObjectType" of IfcWall.
Maybe I am missing something very basic?

[mvdXML test.zip](https://github.com/xBimTeam/XbimMvdXML/files/4109105/mvdXML.test.zip)

**Comment by TobTob-BIM** [comment]
Hi Claudio,

it seems like I have found the reason for this error message. The IfcDoc Tool creates an "applicability" part (see screenshot). 
![applicability](https://user-images.githubusercontent.com/60261788/73162871-0e547980-40ef-11ea-8151-d1e5b926492e.PNG)
By simply deleting this section, the tests can properly run (see screenshot2). Unfortunatly I do not know why IfcDoc is creating this section or how I can influence it in any way other than manually editing the mvdXML.
![xbim test2](https://user-images.githubusercontent.com/60261788/73163438-4c9e6880-40f0-11ea-8bca-bfd8dcc7849b.PNG)


Best regards

Tobias

**Comment by CBenghi** [comment]
Hi Tobias, 
I've changed the code in the library, but I've not come to deploy the plugin yet.
Are you accessing it through the plugin or library?

**Comment by TobTob-BIM** [comment]
Hi Claudio,

Thank you for the changes. I am accessing it through the plugin.

Best regards
Tobias

**Comment by CBenghi** [comment]
Hi Tobias,
try to download the updated plugin in xplorer.
It's in the development channel, see the following image: 

![image](https://user-images.githubusercontent.com/5476273/73825627-9bd54f00-47fc-11ea-8db2-866b83669304.png)

Let me know if it fixes your problem. Soon the v5 version will be available too.

**Comment by TobTob-BIM** [comment]
Hi Claudio,
this fixed my problem. I could run a check with an unedited mvdXML using the new plugin version.
Thank you very much!

Best regards
Tobias
